name: "📚 Documentation"
description: Report a documentation deficiency to help improve the project or suggestions for new workflow.
title: "docs: <title>"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        📚 **Document Updation / Workflow Suggestion**

        Thanks for taking the time to fill out this documentation deficiency report! :memo:
  - type: textarea
    id: description
    attributes:
      label: "Description of the documentation deficiency / workflow suggestion."
      description: Please provide a clear and concise description of what the documentation deficiency / workflow suggestion is.
      placeholder: Short and explicit description of the documentation deficiency / workflow suggestion...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Contributor terms
      description: By submitting this issue, you agree to follow our Contributing Instructions. Please read our [Contributing Instructions](https://github.com/jain-rishabh-21/DoctorVerse/blob/main/Contributing.md).
      options:
        - label: I agree to follow the Contributing Instructions
          required: true
