name: Close Issue on PR Merge
on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close Issue
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Merging PR..."
          ISSUE_NUMBER=$(jq --raw-output .pull_request.issue_url <<< $GITHUB_CONTEXT)
          curl -sSL -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"state": "closed"}' \
            $ISSUE_NUMBER
